title: Mark Vincent Yason
description: Software Reverse Engineer and Vulnerability Researcher | Independent Security Researcher | markyason.github.io
theme: jekyll-theme-minimal
baseurl:
github:
  is_project_page: false
  is_user_page: false
